add filter class for function calls
cognitedata/cognite-sdk-python pull request #1075
Opened 2022-10-26 10:43 UTC by maur1

## Description
Add function calls filter class

### Why:
None is read as filter input and the functions.list_calls() endpoint will not return any function calls. 
functions.calls.list(function_id=xxx) now return a list of calls for the specified function id

### Still a bug to be solved:
Looks like the endpoints returns an empty list if any filter parameters are present

2022-10-26 10:47 UTC, erlendvollset commented
Please also add a test which reproduces the issue.

2022-11-01 14:26 UTC, pavelzubarev commented
@erlendvollset ;)

2022-11-01 16:22 UTC, erlendvollset commented
You will need to bump version and update changelog aswell.

2022-11-17 11:44 UTC, erlendvollset approved these changes
Lgtm!

2022-11-17 11:45 UTC, merged

2022-11-17 11:45 UTC, erlendvollset requested changes
Little too quick

2022-11-17 11:46 UTC, erlendvollset requested changes
Little too quick

2022-11-17 11:46 UTC, erlendvollset commented on pyproject.toml
> +coverage = "^6.5.0"
This should be added to dev dependencies.

2022-11-17 11:46 UTC, erlendvollset commented on pyproject.toml
> +coverage = "^6.5.0"
Or why do we need to add it at all? pytest-cov should cover our needs.