Remove support for legacy auth
cognitedata/cognite-sdk-python pull request #1201
Opened 2023-04-17 09:48 UTC by erlendvollset

- Remove support for api keys and login status
- Remove support for service accounts
- Bump version and update changelog

## Description
Please describe the change you have made.

## Checklist:
- [ ] Tests added/updated.
- [ ] Documentation updated. Documentation is generated from docstrings - these must be updated according to your change.
  If a new method has been added it should be referenced in [cognite.rst](https://github.com/cognitedata/cognite-sdk-python/blob/master/docs/source/cognite.rst) in order to generate docs based on its docstring.
- [ ] Changelog updated in [CHANGELOG.md](https://github.com/cognitedata/cognite-sdk-python/blob/master/CHANGELOG.md).
- [ ] Version bumped. If triggering a new release is desired, bump the version number in [_version.py](https://github.com/cognitedata/cognite-sdk-python/blob/master/cognite/client/_version.py) and [pyproject.toml](https://github.com/cognitedata/cognite-sdk-python/blob/master/pyproject.toml) per [semantic versioning](https://semver.org/).

2023-04-18 08:40 UTC, qTipTip approved these changes
LGTMlops 🚀

2023-04-18 08:56 UTC, haakonvt requested changes
There are a few properties & parameters that should be removed once moving to major version 6. I think it would make sense to hold off on the major version bump for as long as possible, and rather add warnings or similar?

We need to keep in mind each major version bump will keep a loooot of our customers from receiving updates to the SDK for a long time since we do not keep updating v5 with minor/patch releases after moving to 6 😬

2023-04-18 08:56 UTC, haakonvt commented on cognite/client/_cognite_client.py
Remove:
```
@property  # TODO (v6.0.0): Delete this whole property
    def extraction_pipeline_runs(self) -> ExtractionPipelineRunsAPI:
```

2023-04-18 08:56 UTC, haakonvt commented on cognite/client/_cognite_client.py
Remove:
```
@property  # TODO (v6.0.0): Delete this whole property
    def datapoints(self) -> DatapointsAPI:
        if int(self.version.split(".")[0]) >= 6:
```

2023-04-18 08:56 UTC, haakonvt commented on CHANGELOG.md
Remove deprecated camelCase parameter support from:
```
cognite/client/_api/extractionpipelines.py (one use)

cognite/client/data_classes/shared.py (two uses)
```

2023-04-19 08:49 UTC, haakonvt requested changes
Let's also add an entry in `MIGRATION_GUIDE.md` 🚀

2023-04-19 09:01 UTC, haakonvt approved these changes
LGTM. Could you fix the bad date on line 35 in the change log? It should not be November 😅 
```
## [5.11.0] - 17-11-23
```

2023-04-19 09:31 UTC, merged