[DOGE-44] Add helper function to raise first encountered exception in `utils._concurrency.TaskSummary`
cognitedata/cognite-sdk-python pull request #1396
Opened 2023-10-02 11:31 UTC by pratuat

## Description
Please describe the change you have made.

## Checklist:
- [ ] Tests added/updated.
- [ ] Documentation updated. Documentation is generated from docstrings - these must be updated according to your change.
  If a new method has been added it should be referenced in [cognite.rst](https://github.com/cognitedata/cognite-sdk-python/blob/master/docs/source/cognite.rst) in order to generate docs based on its docstring.
- [ ] Changelog updated in [CHANGELOG.md](https://github.com/cognitedata/cognite-sdk-python/blob/master/CHANGELOG.md).
- [x] Version bumped. If triggering a new release is desired, bump the version number in [_version.py](https://github.com/cognitedata/cognite-sdk-python/blob/master/cognite/client/_version.py) and [pyproject.toml](https://github.com/cognitedata/cognite-sdk-python/blob/master/pyproject.toml) per [semantic versioning](https://semver.org/).

2023-10-02 19:35 UTC, haakonvt requested changes
Good change! This will let us more easily fix the issue of not using more narrow exceptions in the next major version bump! 👌

2023-10-03 19:26 UTC, haakonvt commented
I found a few more:

<img width="400" alt="image" src="https://github.com/cognitedata/cognite-sdk-python/assets/8521241/cb97f4dc-5eac-44ab-847a-5922f1019ff3">

2023-10-03 19:27 UTC, haakonvt commented on cognite/client/_api/relationships.py
> +
Consider if adding space above and below is necessary for readability.

2023-10-04 19:22 UTC, pratuat commented
> I found a few more:
> 
> <img alt="image" width="400" src="https://user-images.githubusercontent.com/8521241/272375942-cb97f4dc-5eac-44ab-847a-5922f1019ff3.png">

sorry I missed those and thank you for finding them 👍 :)

2023-10-04 21:02 UTC, haakonvt approved these changes
Lgtm!

2023-10-05 12:18 UTC, merged