Support Custom Property Types
cognitedata/cognite-sdk-python pull request #1811
Opened 2024-06-15 14:19 UTC by doctrino

## Description
Please describe the change you have made.

## Checklist:
- [ ] Tests added/updated.
- [ ] Documentation updated. Documentation is generated from docstrings - these must be updated according to your change.
  If a new method has been added it should be referenced in [cognite.rst](https://github.com/cognitedata/cognite-sdk-python/blob/master/docs/source/cognite.rst) in order to generate docs based on its docstring.
- [ ] Changelog updated in [CHANGELOG.md](https://github.com/cognitedata/cognite-sdk-python/blob/master/CHANGELOG.md).
- [ ] Version bumped. If triggering a new release is desired, bump the version number in [_version.py](https://github.com/cognitedata/cognite-sdk-python/blob/master/cognite/client/_version.py) and [pyproject.toml](https://github.com/cognitedata/cognite-sdk-python/blob/master/pyproject.toml) per [semantic versioning](https://semver.org/).

2024-06-15 18:37 UTC, doctrino commented on cognite/client/data_classes/data_modeling/core.py
> -class DataModelingInstancesList(WriteableCogniteResourceList, Generic[T_WriteClass, T_WritableCogniteResource], ABC):
Needed to move this to add the `T_Proprety` to the list of generics.

2024-06-17 13:42 UTC, erlendvollset requested changes
Instead of making the new generic `NodeApplyBase`, I think we should instead just make the methods/classes expecting a NodeApply generic. So we can have a `TypedNodeApply` base class instead of `PropertyLike` which is accepted anywhere a `NodeApply` is accepted. Then we'll make `client.instances.apply` and `InstancesApplyResult` generic on `T_NodeApply = TypeVar(NodeApply | TypedNodeApply)`. `TypedNodeApply` needs to have the base properties (space, external_id, type, ...) defined then.

2024-06-17 13:45 UTC, erlendvollset commented
Then we could actually envision making `list/retrieve` generic and returning typed instances, as long as we ensure that only 1 source is selected.

2024-07-02 13:36 UTC, doctrino commented
Approach abandoned.

2024-07-02 13:36 UTC, closed without merging