Add support for simulator models
cognitedata/cognite-sdk-python pull request #2068
Opened 2024-12-18 12:38 UTC by abdullah-cognite

## Description
Please describe the change you have made.

## Checklist:
- [ ] Tests added/updated.
- [ ] Documentation updated. Documentation is generated from docstrings - these must be updated according to your change.
  If a new method has been added it should be referenced in [cognite.rst](https://github.com/cognitedata/cognite-sdk-python/blob/master/docs/source/cognite.rst) in order to generate docs based on its docstring.
- [ ] Changelog updated in [CHANGELOG.md](https://github.com/cognitedata/cognite-sdk-python/blob/master/CHANGELOG.md).
- [ ] Version bumped. If triggering a new release is desired, bump the version number in [_version.py](https://github.com/cognitedata/cognite-sdk-python/blob/master/cognite/client/_version.py) and [pyproject.toml](https://github.com/cognitedata/cognite-sdk-python/blob/master/pyproject.toml) per [semantic versioning](https://semver.org/).

2025-01-20 10:05 UTC, evertoncolling commented on cognite/client/_api/simulators/models.py
> +            filter (SimulatorModelRevisionsFilter | dict[str, Any] | None): Filter to apply.
```suggestion
            limit (int): Maximum number of results to return. Defaults to 10. Set to -1, float(“inf”) or None to return all items.
            sort (CreatedTimeSort | None): The criteria to sort by.
            filter (SimulatorModelRevisionsFilter | dict[str, Any] | None): Filter to apply.
```

2025-01-20 10:06 UTC, evertoncolling commented on cognite/client/_api/simulators/models.py
> +                >>> res = client.simulators.models.revisions.list()
```suggestion
                >>> from cognite.client import CogniteClient
                >>> client = CogniteClient()
                >>> res = client.simulators.models.revisions.list()
```

2025-01-20 10:11 UTC, evertoncolling commented on cognite/client/_api/simulators/models.py
> +            SimulatorModelRevision | SimulatorModelRevisionList | None: Requested simulator model revision
```suggestion
            SimulatorModelRevision | SimulatorModelRevisionList | None: Requested simulator model revision(s).
```

2025-01-20 10:12 UTC, evertoncolling commented on cognite/client/_api/simulators/models.py
> +                >>> res = client.simulators.models.revisions.retrieve(external_id="model_external_id")
```suggestion
        Examples:
            Get simulator model revision by id:
                >>> from cognite.client import CogniteClient
                >>> client = CogniteClient()
                >>> res = client.simulators.models.revisions.retrieve(id=123)

            Get simulator model revision by external id:
                >>> res = client.simulators.models.revisions.retrieve(external_id="model_external_id")
                
            Get multiple simulator model revisions by external ids:
                >>> res = client.simulators.models.revisions.retrieve(external_id=["a", "b"])
```

2025-01-20 10:13 UTC, evertoncolling commented on cognite/client/_api/simulators/models.py
> +    def retrieve(self, external_id: SequenceNotStr[str], id: int | None = None) -> SimulatorModelRevisionList: ...
Any reason why we support only a list of External IDs and not a list of IDs?

2025-01-20 10:16 UTC, evertoncolling commented on cognite/client/_api/simulators/models.py
> +            models (SimulatorModel | SimulatorModelWrite | Sequence[SimulatorModel] | Sequence[SimulatorModelWrite]): Models to create.
```suggestion
            models (SimulatorModel | SimulatorModelWrite | Sequence[SimulatorModel] | Sequence[SimulatorModelWrite]): Model(s) to create.
```

2025-01-20 10:18 UTC, evertoncolling commented on cognite/client/_api/simulators/models.py
> +            external_ids (str | SequenceNotStr[str] | None): External External ids of the models to delete.
```suggestion
            ids (int | Sequence[int] | None): ids (or sequence of ids) for the model(s) to delete.
            external_ids (str | SequenceNotStr[str] | None): external ids (or sequence of external ids) for the model(s) to delete.
```

2025-01-20 10:19 UTC, evertoncolling commented on cognite/client/data_classes/simulators/models.py
> +        id (int): No description.
```suggestion
        id (int): Internal id of the simulator model revision
```

2025-01-20 10:20 UTC, evertoncolling commented on cognite/client/data_classes/simulators/models.py
> +        simulator_external_id (str): No description.
```suggestion
        simulator_external_id (str): External id of the simulator associated with the model revision
```

2025-01-20 10:21 UTC, evertoncolling commented on cognite/client/data_classes/simulators/models.py
> +        status_message (str | None): The current status of the model revision
```suggestion
        status_message (str | None): The current status message of the simulator model revision
```

2025-01-20 10:27 UTC, polomani commented on CHANGELOG.md
>  - Support for the `/simulators` and `/simulators/integration` API endpoints.
need to fix the log entry for v7.71.3

2025-01-20 10:28 UTC, polomani commented on CHANGELOG.md
>  - Support for the `/simulators` and `/simulators/integration` API endpoints.
damn (version bump is not semantically correct :( )

2025-01-20 10:29 UTC, polomani commented on cognite/client/_cognite_client.py
> +        self.simulators.models = SimulatorModelsAPI(self._config, self._API_VERSION, self)
this should be initiated inside of `class SimulatorsAPI`, and it seems like it already is

2025-01-20 10:36 UTC, polomani commented on tests/tests_integration/test_api/test_simulators/conftest.py
> +    model_exists = any(model.external_id == model_unique_external_id for model in models)
why not using get by id?

2025-01-20 10:41 UTC, polomani commented on tests/tests_integration/test_api/test_simulators/conftest.py
> +                        "externalId": model_revision_unique_external_id,
```suggestion
                        "description": "test sim model revision description",,
                        "fileId": seed_file.id,
                        "modelExternalId": model_unique_external_id,
                        "externalId": model_revision_unique_external_id,
```

here is the definition of `simulator_model_revision`
```
simulator_model_revision = {
    "externalId": resource_names["simulator_model_revision_external_id"],
    "modelExternalId": resource_names["simulator_model_external_id"],
    "description": "test sim model revision description",
    "fileId": 00000000000000,
}
```

3 out of 4 params are overridden, therefore no need of it, I presume

2025-01-20 10:45 UTC, polomani commented on tests/tests_integration/test_api/test_simulators/conftest.py
> +            name="ShowerMixer.dwxmz",
```suggestion
            path="tests/tests_integration/test_api/test_simulators/seed/ShowerMixer.txt",
            external_id=seed_resource_names["simulator_model_file_external_id"],
            name="ShowerMixer.txt",
```

2025-01-20 11:25 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +            filter (SimulatorModelRevisionsFilter | dict[str, Any] | None): Filter to apply.
Applied

2025-01-20 11:25 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +                >>> res = client.simulators.models.revisions.list()
Applied

2025-01-20 11:26 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +            id (int | None): The id of the simulator model revision.
applied

2025-01-20 11:26 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +            SimulatorModelRevision | SimulatorModelRevisionList | None: Requested simulator model revision
applied

2025-01-20 11:28 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +            external_ids (str | SequenceNotStr[str] | None): External External ids of the models to delete.
applied

2025-01-20 11:31 UTC, abdullah-cognite commented on cognite/client/data_classes/simulators/models.py
> +        id (int): No description.
applied

2025-01-20 11:31 UTC, abdullah-cognite commented on cognite/client/data_classes/simulators/models.py
> +        simulator_external_id (str): No description.
applied

2025-01-20 11:31 UTC, abdullah-cognite commented on cognite/client/data_classes/simulators/models.py
> +        status_message (str | None): The current status of the model revision
applied

2025-01-20 11:43 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +    def retrieve(self, external_id: SequenceNotStr[str], id: int | None = None) -> SimulatorModelRevisionList: ...
We have just followed how most of the other resources have implemented this function. Do you think our users would have need for retrieving by multiple ids?

2025-01-20 11:44 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +    def retrieve(self, external_id: SequenceNotStr[str], id: int | None = None) -> SimulatorModelRevisionList: ...
We have just followed how most of the other resources have implemented this function. Do you think our users would have need for retrieving by multiple ids?

2025-01-20 13:19 UTC, evertoncolling commented on cognite/client/_api/simulators/models.py
> +    def retrieve(self, external_id: SequenceNotStr[str], id: int | None = None) -> SimulatorModelRevisionList: ...
No, I was just curious. I checked the other endpoints in the SDK and most implement both support for multiple Ids and ExternalIds, but I don't have a strong opinion, as I never needed to fetch multiple by Id. As long as it's documented it should be fine.

2025-01-20 14:12 UTC, polomani commented on cognite/client/_api/simulators/models.py
> +    def retrieve(self, external_id: SequenceNotStr[str], id: int | None = None) -> SimulatorModelRevisionList: ...
either both arrays, of both single items, strange that we have it mixed? one is array and one is not

<img width="878" alt="Screenshot 2025-01-20 at 15 11 15" src="https://github.com/user-attachments/assets/2498d44c-3b31-4847-9a07-82c62ecca052" />
<img width="611" alt="Screenshot 2025-01-20 at 15 11 05" src="https://github.com/user-attachments/assets/2d128fd4-ec02-4149-83b4-ee3c4ffc6ef8" />

2025-01-21 07:32 UTC, abdullah-cognite commented on tests/tests_integration/test_api/test_simulators/conftest.py
> +            name="ShowerMixer.dwxmz",
done

2025-01-21 07:52 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +    def retrieve(self, external_id: SequenceNotStr[str], id: int | None = None) -> SimulatorModelRevisionList: ...
Yeah, dumb me, just took it from the last PR we had created had and assumed all other resources were doing the same

2025-01-21 07:56 UTC, abdullah-cognite commented on cognite/client/_version.py
> +__version__ = "7.72.2"
Should we just bump the minor?

2025-01-21 07:58 UTC, evertoncolling commented on cognite/client/_api/simulators/models.py
> +    def retrieve(self, external_id: SequenceNotStr[str], id: int | None = None) -> SimulatorModelRevisionList: ...
It's nice to have both retrieve and retrieve_multiple for all resources, as the user can avoid writing for loops and making unnecessary requests.

2025-01-21 10:55 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +    def retrieve(self, external_id: SequenceNotStr[str], id: int | None = None) -> SimulatorModelRevisionList: ...
done, ive modified both our resources to have both `retrieve` and `retrieve_multiple` following the assets resource.

2025-01-24 11:44 UTC, haakonvt requested changes
Is this the final PR adding simulators or are there more parts coming?

2025-01-24 11:44 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +    ) -> SimulatorModelRevision | SimulatorModelRevisionList:
Let's just accept WRITE versions in the create-method

2025-01-24 11:44 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +        assert_type(revisions, "simulator_model_revision", [SimulatorModelRevisionCore, SimulatorModelRevisionWrite])
Two questions:
1. Why do you specify both SimulatorModelRevisionCore and its subclass SimulatorModelRevisionWrite?
2. The create method says "...or list of Simulator models to create". The current code would block that I think

2025-01-24 11:44 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +            limit (int): Maximum number of results to return. Defaults to 10. Set to -1, float(“inf”) or None to return all items.
```suggestion
            limit (int): Maximum number of results to return. Defaults to 25. Set to -1, float(“inf”) or None to return all items.
```

2025-01-24 11:44 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +                    ... )
Specify filter *and sort order* 👀

2025-01-24 11:44 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +            method="POST",
```suggestion
```

2025-01-24 11:44 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +        self, ids: Sequence[int] | None = None, external_ids: SequenceNotStr[str] | None = None
See other comment regarding retrieve_multiple

2025-01-24 11:44 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +    ) -> Iterator[SimulatorModel]: ...
This looks wrong. If an int is specified (assuming != 1) `SimulatorModelList` should be returned?

2025-01-24 11:44 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +        """`Create simulator models <https://developer.cognite.com/api#tag/Simulator-Models/operation/create_simulator_model_simulators_models_post>`_
I won't comment on this more, but let's fix all occurrences of:
1. Only use Writer classes in create or apply methods
2. Overloads that handle single inputs should not have lists as outputs

2025-01-24 11:44 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +        You can create an arbitrary number of simulator models, and the SDK will split the request into multiple requests.
Implementation details do not belong here
```suggestion
```

2025-01-24 11:44 UTC, haakonvt commented on tests/tests_integration/test_api/test_simulators/test_models.py
> +        # quick test of the iterator
```suggestion
```

2025-01-24 11:44 UTC, haakonvt commented on tests/tests_integration/test_api/test_simulators/test_models.py
> +        model_external_id_2 = datetime.datetime.now().strftime("%Y%m%d%H%M%S2")
Better to use a real random identifier (we have a lot of parallel test runners, and a collision on a specific second is actually likely)
`from cognite.client.utils._text import random_string`
```suggestion
        model_external_id_1 = random_string(10)
        model_external_id_2 = random_string(10)
```

2025-01-24 11:44 UTC, haakonvt commented on tests/tests_integration/test_api/test_simulators/test_models.py
> +        models_created.name = "updated name"  # Update the name
Please try to use comments when e.g. the code does something counter-intuitive or when it is very hard to read 😄 
```suggestion
        assert models_created.external_id == model_external_id
        models_created.description = "updated description"
        models_created.name = "updated name"
```

2025-01-24 14:40 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +            method="POST",
doesnt work without the method : `TypeError: APIClient._list() missing 1 required positional argument: 'method'`

2025-01-25 18:09 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +    ) -> SimulatorModelRevision | SimulatorModelRevisionList: ...
Yes, but check return type annotation

2025-01-25 18:10 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +            method="POST",
Oh my bad 😅

2025-02-04 20:19 UTC, abdullah-cognite commented on cognite/client/data_classes/simulators/models.py
> +        status_message: str | None = None,
they shouldnt be, removed

2025-02-04 20:23 UTC, abdullah-cognite commented
> Is this the final PR adding simulators or are there more parts coming?

There are 2 more remaining parts

2025-02-04 21:19 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +    ) -> Iterator[SimulatorModel]: ...
Updated overload signature

2025-02-04 21:28 UTC, abdullah-cognite commented on tests/tests_integration/test_api/test_simulators/conftest.py
> +    # Only create if model doesn't exist
we shouldnt have used `_post`, removed

2025-02-04 22:29 UTC, abdullah-cognite commented on cognite/client/_version.py
> +__version__ = "7.72.2"
Just removed this and moved the entry back to unreleased

2025-02-04 22:39 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +        assert_type(revisions, "simulator_model_revision", [SimulatorModelRevisionCore, SimulatorModelRevisionWrite])
1 and 2 - I initially didn’t fully grasp how the core and write classes were connected, but I’ve (sort of 🙈 ) figured it out now. Sorry about that!

2025-02-05 09:56 UTC, haakonvt reviewed
Starting to look good, just some more polishing and this looks ready!

2025-02-05 09:56 UTC, haakonvt commented on CHANGELOG.md
>  ## [7.71.2] - 2025-01-07
Missing a newline here

2025-02-05 09:56 UTC, haakonvt commented on cognite/client/_api/simulators/integrations.py
> +        external_id: str | SequenceNotStr[str] | SequenceNotStr[str] | None = None,
```suggestion
        external_id: str | SequenceNotStr[str] | None = None,
```

2025-02-05 09:56 UTC, haakonvt commented on cognite/client/_api/simulators/integrations.py
> +            external_id (str | SequenceNotStr[str] | SequenceNotStr[str] | None): No description.
```suggestion
            external_id (str | SequenceNotStr[str] | None): External_id(s) of simulator integrations to delete
```

2025-02-05 09:56 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +                    ...     sort=CreatedTimeSort(order="asc")
`CreatedTimeSort` is not imported. If the doctests aren't picking this up, it means you need to update:
`tests/tests_unit/test_docstring_examples.py`

2025-02-05 09:56 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +                >>> res = client.simulators.models.revisions.retrieve(external_ids=["revision1", "revision2"])
See previous comment, these should raise in doctests
```suggestion
                >>> res = client.simulators.models.revisions.retrieve(external_id=["revision1", "revision2"])
```

2025-02-05 09:57 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +                >>> res = client.simulators.models.revisions.retrieve(external_ids=["revision1", "revision2"])
Please check if there are more occurrences of the above

2025-02-06 09:51 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +                    ...     sort=CreatedTimeSort(order="asc")
Added

2025-02-06 09:51 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models.py
> +                >>> res = client.simulators.models.revisions.retrieve(external_ids=["revision1", "revision2"])
Fixed

2025-02-06 09:52 UTC, abdullah-cognite commented on CHANGELOG.md
>  ## [7.71.2] - 2025-01-07
fixed

2025-02-06 11:05 UTC, haakonvt requested changes

2025-02-06 11:05 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +    def retrieve(self, id: int | None = None, external_id: str | None = None) -> SimulatorModel | None: ...
This overload allows "if single id and single external id" -> "SimulatorModel is returned".

I think you actually need to break this into 3, something like this:

```py
from typing import NoReturn

@overload
def retrieve(self, id: None = None, external_id: None = None) -> NoReturn: ...

@overload
def retrieve(self, id: int, external_id: None = None) -> SimulatorModel | None: ...

@overload
def retrieve(self, id: None = None, external_id: str) -> SimulatorModel | None: ...
```

2025-02-06 11:05 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +    ) -> Iterator[SimulatorModelRevision]: ...
Should probably return list if an integer chunk size is given

2025-02-06 11:05 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +            )
See other comment

2025-02-06 11:05 UTC, haakonvt commented on cognite/client/_api/simulators/models.py
> +    def retrieve(self, id: int | None = None, external_id: str | None = None) -> SimulatorModelRevision | None: ...
See other comment

2025-02-07 14:36 UTC, haakonvt approved these changes
Great job! 💯 One last nice-to-have comment for you

2025-02-07 14:36 UTC, haakonvt commented on cognite/client/_api/simulators/models_revisions.py
> +                >>> from cognite.client.data_classes.simulators.models import CreatedTimeSort
I think it would be nice if these are importable from `data_classes.simulators` directly:
```suggestion
                >>> from cognite.client.data_classes.simulators import SimulatorModelRevisionsFilter
                >>> from cognite.client.data_classes.simulators import CreatedTimeSort
```

2025-02-10 10:14 UTC, abdullah-cognite commented on cognite/client/_api/simulators/models_revisions.py
> +                >>> from cognite.client.data_classes.simulators.models import CreatedTimeSort
done :)

2025-02-10 18:39 UTC, merged