Chain requests for big relationships filters
cognitedata/cognite-sdk-python pull request #771
Opened 2020-12-02 20:29 UTC by andreavs

2020-12-02 20:38 UTC, sanderland commented on cognite/client/_api/relationships.py
> +            for res in res_list:
I think there is a joined_results thingy that's more normal here

2020-12-02 20:39 UTC, sanderland commented on tests/tests_unit/test_api/test_relationships.py
> +        assert set([s for s in source_external_ids]) == set(requested_sources)
i like this test

2020-12-02 20:39 UTC, sanderland requested changes
one comment
+changelog
+version

2020-12-02 20:53 UTC, caelyn-cognite commented
I doubt anyone is going to be attempting to filter on a large number of data sets or labels anytime soon; but we should keep this approach in mind if/when that becomes relevant.

2020-12-03 10:06 UTC, sanderland approved these changes

2020-12-03 13:40 UTC, merged