Add List 3D Nodes query parameters
cognitedata/cognite-sdk-python pull request #795
Opened 2021-03-10 13:36 UTC by haakonflatval-cognite

2021-03-12 12:00 UTC, haakonflatval-cognite commented
The reason for the changes to `cognite/client/_api_client.py`, is that the function `get_partition()` previously only supported getting partitions through the HTTP `POST` method, while `List 3D Nodes` expects `GET`.

2021-03-12 12:25 UTC, sanderland commented on cognite/client/_api_client.py
> +                    params = filter.copy()
params = {**filter.copy(),
              "limit": ...
              "cursor": ...
                **other_params}

2021-03-12 12:25 UTC, sanderland requested changes
one refactoring suggestion, and would like a test

2021-03-12 12:26 UTC, me-ydv-5 reviewed
Please also add changelog and update version.

2021-03-15 12:56 UTC, haakonflatval-cognite commented
The test is currently skipped, just as the rest of the revision tests. This is because we don't have a setup for creating a revision with a 3d file. Adding such a setup is out of scope of this PR.

2021-03-16 08:09 UTC, sanderland commented on cognite/client/_api/three_d.py
> +        limit: int = 25,
I think we tend to keep limit as the last parameter, as it makes the docs a little more readable

2021-03-16 08:10 UTC, sanderland requested changes
tiny change i missed before

2021-03-16 08:12 UTC, sanderland approved these changes

2021-03-16 08:22 UTC, merged