add filter params to raw()
cognitedata/cognite-sdk-python pull request #824
Opened 2021-05-13 06:18 UTC by tgib23

This PR adds filter params to raw() method to support the same params as list() does.

Reference : #820

2021-05-15 08:45 UTC, erlendvollset requested changes
Nice! Thanks for doing this!

2021-05-15 08:45 UTC, erlendvollset commented on tests/tests_integration/test_api/test_raw.py
> +            assert {"c1", "c2"} == set(row.columns.keys())
Better to split it into a separate test: `test_iter_rows_cols`

2021-05-15 08:45 UTC, erlendvollset commented on tests/tests_unit/test_api/test_raw.py
> +    def test_row(self, mock_raw_row_response):
```suggestion
    def test_iter(self, mock_raw_row_response):
```

2021-05-15 08:45 UTC, erlendvollset commented on tests/tests_unit/test_api/test_raw.py
> +    def test_rows_cols(self, mock_raw_row_response):
```suggestion
    def test_iter_cols(self, mock_raw_row_response):
```

2021-05-15 08:45 UTC, erlendvollset commented on tests/tests_unit/test_api/test_raw.py
> +    def test_rows_cols_empty(self, mock_raw_row_response):
```suggestion
    def test_iter_cols_empty(self, mock_raw_row_response):
```

2021-05-15 08:45 UTC, erlendvollset commented on tests/tests_unit/test_api/test_raw.py
> +    def test_rows_cols_str_not_supported(self, mock_raw_row_response):
```suggestion
    def test_iter_cols_str_not_supported(self, mock_raw_row_response):
```

2021-05-15 08:45 UTC, erlendvollset commented on cognite/client/_api/raw.py
> +                columns = ",".join([str(x) for x in columns])
Code duplicated in `list()` method, extract into a protected method.

2021-05-17 06:55 UTC, tgib23 commented
@erlendvollset thanks for your review. I think I've fixed the whole you pointed out.

2021-05-21 11:34 UTC, erlendvollset reviewed
Just some nitpick. Please update the changelog aswell (and bump version number if you want to trigger a new release)

2021-05-21 11:34 UTC, erlendvollset commented on cognite/client/_api/raw.py
> +        if not isinstance(columns, List):
```suggestion
    def _make_columns_param(self, columns: Optional[List[str]]) -> Optional[str]:
        if columns is None:
            return None
        if not isinstance(columns, List):
```

2021-05-21 11:34 UTC, erlendvollset commented on cognite/client/_api/raw.py
> +        if not isinstance(columns, List):
And then remove the `if columns is not None` check from `list()` and `__iter__()`

2021-06-04 01:12 UTC, tgib23 commented
@erlendvollset I've pushed the changes. Please let me know if there is anything else to change.

2021-06-04 08:52 UTC, erlendvollset approved these changes
LGTM. You need to update the version in cognite/client/_version.py in order for a new release to be made.

2021-06-04 08:53 UTC, erlendvollset commented on CHANGELOG.md
> +## [2.19.1] - 2021-05-27
```suggestion
## [2.19.1] - 2021-06-04
```

2021-06-04 08:56 UTC, erlendvollset commented
> LGTM. You need to update the version in cognite/client/_version.py in order for a new release to be made.

I updated it now.

2021-06-07 15:10 UTC, merged

2021-06-08 15:04 UTC, tgib23 commented
@erlendvollset thanx for your help!