Add dataSetId to template group
cognitedata/cognite-sdk-python pull request #857
Opened 2021-09-28 16:19 UTC by Tapped

## Description
Please describe the change you have made.

## Checklist:
- [ ] Tests added/updated.
- [ ] Documentation updated. Documentation is generated from docstrings - these must be updated according to your change. 
  If a new method has been added it should be referenced in [cognite.rst](https://github.com/cognitedata/cognite-sdk-python/blob/master/docs/source/cognite.rst) in order to generate docs based on its docstring. 
- [ ] Changelog updated in [CHANGELOG.md](https://github.com/cognitedata/cognite-sdk-python/blob/master/CHANGELOG.md).
- [ ] Version bumped. If triggering a new release is desired, bump the version number in [_version.py](https://github.com/cognitedata/cognite-sdk-python/blob/master/cognite/client/_version.py) per [semantic versioning](https://semver.org/).

2021-09-29 11:52 UTC, erlendvollset requested changes

2021-09-29 11:52 UTC, erlendvollset commented on cognite/client/data_classes/templates.py
> +        dataSetId: int = None,
snake_case

2021-09-30 07:25 UTC, Tapped commented on cognite/client/data_classes/templates.py
> +        dataSetId: int = None,
Thank you!

2021-10-05 16:46 UTC, erlendvollset approved these changes

2021-10-05 17:19 UTC, merged