[CDF-13342] Fix doc typo
cognitedata/cognite-sdk-python pull request #860
Opened 2021-09-30 14:19 UTC by aurlien

## Description
Please describe the change you have made.

## Checklist:
- [ ] Tests added/updated.
- [ ] Documentation updated. Documentation is generated from docstrings - these must be updated according to your change. 
  If a new method has been added it should be referenced in [cognite.rst](https://github.com/cognitedata/cognite-sdk-python/blob/master/docs/source/cognite.rst) in order to generate docs based on its docstring. 
- [ ] Changelog updated in [CHANGELOG.md](https://github.com/cognitedata/cognite-sdk-python/blob/master/CHANGELOG.md).
- [ ] Version bumped. If triggering a new release is desired, bump the version number in [_version.py](https://github.com/cognitedata/cognite-sdk-python/blob/master/cognite/client/_version.py) per [semantic versioning](https://semver.org/).

2021-10-01 09:03 UTC, me-ydv-5 approved these changes

2021-10-01 09:04 UTC, me-ydv-5 commented
this won't directly start reflecting in the docs, there's some manual step (automatic but broken atm) that generates json docs and then you copy that json docs to service-contract repo. if it's urgent i can do it today.

2021-10-01 09:20 UTC, aurlien commented
Thanks, @me-ydv-5! I don't think it's urgent to get it out. 

/cc @Tapped

2021-10-01 13:08 UTC, erlendvollset commented
The pysdk docs will be automatically updated through the readthedocs webhook though.

2021-10-04 11:01 UTC, nayang-cognite requested changes

2021-10-04 11:01 UTC, nayang-cognite commented on cognite/client/_api/templates.py
>                  >>>    '''
User also mentioned missing some []’ for datapoints, cannot find your fix for the mentioned typo here

2021-10-04 11:16 UTC, nayang-cognite approved these changes

2021-10-04 11:17 UTC, merged