Geo dependencies optional
cognitedata/cognite-sdk-python pull request #888
Opened 2022-01-24 10:43 UTC by doctrino

## Description
I have moved `shapely `and `geopandas `as optional dependencies, available with the option `geo`.

## Checklist:
- [- ] Tests added/updated. Not relevant. 
- [x ] Documentation updated. Documentation is generated from docstrings - these must be updated according to your change. 
  If a new method has been added it should be referenced in [cognite.rst](https://github.com/cognitedata/cognite-sdk-python/blob/master/docs/source/cognite.rst) in order to generate docs based on its docstring. 
- [x] Changelog updated in [CHANGELOG.md](https://github.com/cognitedata/cognite-sdk-python/blob/master/CHANGELOG.md).
- [x] Version bumped. If triggering a new release is desired, bump the version number in [_version.py](https://github.com/cognitedata/cognite-sdk-python/blob/master/cognite/client/_version.py) per [semantic versioning](https://semver.org/).

2022-01-24 13:03 UTC, erlendvollset requested changes

2022-01-24 17:23 UTC, doctrino commented on setup.py
> +    extras_require={
Done. Moved to setup-core.

2022-01-24 17:27 UTC, doctrino commented on README.md
> +```
Done.

2022-01-25 07:58 UTC, erlendvollset approved these changes
LGTM 🚀

2022-01-25 10:04 UTC, erlendvollset commented on tests/tests_integration/test_api/test_transformations/test_notifications.py
> +    @pytest.mark.xfail
You can add this annotation on the class itself.
i.e.
```
@pytest.mark.xfail
class TestTransformationNotificationsApi:
    ...
```

2022-01-25 10:06 UTC, erlendvollset commented on tests/tests_integration/test_api/test_transformations/test_notifications.py
> +    @pytest.mark.xfail
or on a module by doing
pytestmarks = [pytest.mark.xfail]

2022-01-25 10:25 UTC, merged